apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # labels of deployement resource
  labels:
    app: frontend
    tier: frontend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
     app: frontend
     tier: frontend
     project: expense
  template:
    metadata:
      labels:
       app: frontend
       tier: frontend
       project: expense
    spec:
      containers:
      - name: nginx
        image: ramki2537/frontend:1.1.0
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec: 
  type: LoadBalancer
  selector:
     app: frontend
     tier: frontend
     project: expense
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80